#!/usr/bin/env node
// Universal MCP configurator: registers the project's MCP servers into every
// supported agentic frontend (Claude Code, OpenAI Codex, OpenCode, Nanocoder,
// VS Code, Cursor) with per-CLI native syntax. Machine-local configs are
// regenerated (idempotently, transactionally, chmod 600) so they survive
// devcontainer rebuilds and fresh clones without committing secrets.
//
// Usage:
//   node .llm/mcp/configure.mjs [--check]
//     --check  Print the plan without writing files.
//
// Credentials come from the environment with .env.local fallback (the
// config files reference env vars; nothing secret is written to disk).
//
// Unity uses the official Unity CLI MCP server (`unity mcp`, ~140 tools on a
// typical project). Container frontends reach it through the host HTTP bridge
// (npm run unity:mcp:host → http://host.docker.internal:9020/mcp); host-side
// GUI clients (Cursor/Windsurf/Claude Desktop) should use the CLI directly via
// `unity mcp configure <client>` on the host.

import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const WORKSPACE_ROOT = process.env.DATAVIZ_MCP_WORKSPACE
    ? path.resolve(process.env.DATAVIZ_MCP_WORKSPACE)
    : path.resolve(SCRIPT_DIR, "..", "..");
const CHECK_ONLY = process.argv.includes("--check");

// ---------------------------------------------------------------------------
// Environment
// ---------------------------------------------------------------------------

function readEnvLocal(filePath) {
    const vars = {};
    let text;
    try {
        text = fs.readFileSync(filePath, "utf8");
    } catch {
        return vars;
    }
    // Tolerate UTF-8 BOM, CRLF endings, and `export ` prefixes.
    text = text.replace(/^\uFEFF/, "").replace(/\r\n/g, "\n").replace(/\r/g, "\n");
    for (const rawLine of text.split("\n")) {
        const line = rawLine.trim();
        if (!line || line.startsWith("#")) continue;
        const eq = line.indexOf("=");
        if (eq <= 0) continue;
        let key = line.slice(0, eq).trim();
        if (key.startsWith("export ")) key = key.slice(7).trim();
        let value = line.slice(eq + 1).trim();
        if (
            (value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))
        ) {
            value = value.slice(1, -1);
        }
        if (key) vars[key] = value;
    }
    return vars;
}

const envLocal = readEnvLocal(path.join(WORKSPACE_ROOT, ".env.local"));
function env(name) {
    return process.env[name] || envLocal[name] || "";
}

function isContainer() {
    return (
        fs.existsSync("/.dockerenv") ||
        fs.existsSync("/run/.containerenv") ||
        process.env.DATAVIZ_IN_CONTAINER === "1"
    );
}

function hasCommand(command) {
    try {
        execFileSync(
            "/bin/bash",
            ["-c", `command -v ${(command)} >/dev/null 2>&1`],
            { stdio: "ignore" },
        );
        return true;
    } catch {
        return false;
    }
}

function ensureUnityMcpToken() {
    const existing = env("UNITY_MCP_TOKEN");
    if (existing) return existing;
    if (CHECK_ONLY) return "(generated)";
    const token = crypto.randomBytes(24).toString("hex");
    const envLocalPath = path.join(WORKSPACE_ROOT, ".env.local");
    let content = "";
    try {
        content = fs.readFileSync(envLocalPath, "utf8");
    } catch {
        content = "# Machine-local credentials (gitignored).\n";
    }
    if (content.length > 0 && !content.endsWith("\n")) content += "\n";
    content += `\n# Auto-generated by configure.mjs on ${new Date().toISOString()}\nUNITY_MCP_TOKEN=${token}\n`;
    fs.mkdirSync(path.dirname(envLocalPath), { recursive: true });
    fs.writeFileSync(envLocalPath, content, { mode: 0o600 });
    return token;
}

// The Z.ai credential circulates under two names: the MCP configs and the
// devcontainer remoteEnv forward use ZAI_API_KEY, while the official
// @z_ai/mcp-server reads Z_AI_API_KEY first. Mirror whichever one exists into
// the other (in .env.local) so every harness and server sees the key.
function ensureZaiKeyAlias() {
    const canonical = env("ZAI_API_KEY");
    const alternate = env("Z_AI_API_KEY");
    if (!canonical && !alternate) return "missing";
    if (canonical && alternate) return "configured";
    if (CHECK_ONLY) return "alias-pending";
    const [missingKey, value] = canonical
        ? ["Z_AI_API_KEY", canonical]
        : ["ZAI_API_KEY", alternate];
    const envLocalPath = path.join(WORKSPACE_ROOT, ".env.local");
    let content = "";
    try {
        content = fs.readFileSync(envLocalPath, "utf8").replace(/^\uFEFF/, "");
    } catch {
        content = "# Machine-local credentials (gitignored).\n";
    }
    if (content.length > 0 && !content.endsWith("\n")) content += "\n";
    content += `\n# Auto-generated alias by configure.mjs on ${new Date().toISOString()}\n${missingKey}=${value}\n`;
    fs.mkdirSync(path.dirname(envLocalPath), { recursive: true });
    fs.writeFileSync(envLocalPath, content, { mode: 0o600 });
    return "aliased";
}

// ---------------------------------------------------------------------------
// Managed server catalog
// ---------------------------------------------------------------------------

const ZAI_IMAGE_SCRIPT = path.join(WORKSPACE_ROOT, ".llm", "mcp", "zai-image-mcp.mjs");
const NODE_BIN = process.execPath;
const HAS_UVX = hasCommand("uvx");
// Container agents reach the host HTTP bridge via host.docker.internal; when
// the configurator runs on the host itself, the bridge is plain loopback.
const UNITY_MCP_URL =
    process.env.UNITY_MCP_HTTP_URL ||
    `http://${isContainer() ? "host.docker.internal" : "127.0.0.1"}:9020/mcp`;

function buildCatalog() {
    const servers = new Map();
    servers.set("unity", {
        summary: `Unity official CLI MCP (unity mcp, ~140 tools) via HTTP bridge ${UNITY_MCP_URL}`,
        claude: {
            type: "http",
            url: UNITY_MCP_URL,
            headers: {
                Authorization: "Bearer ${UNITY_MCP_TOKEN:-}",
            },
        },
        codex: {
            url: UNITY_MCP_URL,
            bearer_token_env_var: "UNITY_MCP_TOKEN",
        },
        opencode: {
            type: "remote",
            url: UNITY_MCP_URL,
            enabled: true,
            oauth: false,
            timeout: 300000,
            headers: {
                Authorization: "Bearer {env:UNITY_MCP_TOKEN}",
            },
        },
        nanocoder: {
            transport: "http",
            url: UNITY_MCP_URL,
            headers: {
                Authorization: "Bearer ${UNITY_MCP_TOKEN:-}",
            },
        },
        vscode: {
            type: "http",
            url: UNITY_MCP_URL,
            headers: {
                Authorization: "Bearer ${env:UNITY_MCP_TOKEN}",
            },
        },
        // Cursor runs on the host, so it can launch the CLI directly (stdio)
        // without going through the HTTP bridge. `unity mcp configure cursor`
        // on the host rewrites this with the absolute CLI path if `unity` is
        // not on the host PATH.
        cursor: { command: "unity", args: ["mcp"] },
    });
    servers.set("github", {
        summary: "GitHub platform (repos, PRs, issues, actions, security…) via hosted MCP, all toolsets",
        claude: {
            type: "http",
            url: "https://api.githubcopilot.com/mcp/",
            headers: {
                Authorization: "Bearer ${GITHUB_PERSONAL_ACCESS_TOKEN:-}",
                "X-MCP-Toolsets": "all",
            },
        },
        codex: {
            url: "https://api.githubcopilot.com/mcp/",
            bearer_token_env_var: "GITHUB_PERSONAL_ACCESS_TOKEN",
            http_headers: { "X-MCP-Toolsets": "all" },
        },
        opencode: {
            type: "remote",
            url: "https://api.githubcopilot.com/mcp/",
            enabled: true,
            oauth: false,
            headers: {
                Authorization: "Bearer {env:GITHUB_PERSONAL_ACCESS_TOKEN}",
                "X-MCP-Toolsets": "all",
            },
        },
        nanocoder: {
            transport: "http",
            url: "https://api.githubcopilot.com/mcp/",
            headers: {
                Authorization: "Bearer ${GITHUB_PERSONAL_ACCESS_TOKEN:-}",
                "X-MCP-Toolsets": "all",
            },
        },
        vscode: {
            type: "http",
            url: "https://api.githubcopilot.com/mcp/",
            headers: {
                Authorization: "Bearer ${env:GITHUB_PERSONAL_ACCESS_TOKEN}",
                "X-MCP-Toolsets": "all",
            },
        },
        cursor: {
            url: "https://api.githubcopilot.com/mcp/",
            headers: {
                Authorization: "Bearer ${env:GITHUB_PERSONAL_ACCESS_TOKEN}",
                "X-MCP-Toolsets": "all",
            },
        },
    });
    servers.set("context7", {
        summary: "Up-to-date library docs for LLMs (Upstash)",
        claude: {
            type: "stdio",
            command: "npx",
            args: ["-y", "@upstash/context7-mcp"],
            env: { CONTEXT7_API_KEY: "${CONTEXT7_API_KEY:-}" },
        },
        codex: {
            command: "npx",
            args: ["-y", "@upstash/context7-mcp"],
            env_vars: ["CONTEXT7_API_KEY"],
        },
        opencode: {
            type: "local",
            command: ["npx", "-y", "@upstash/context7-mcp"],
            enabled: true,
            timeout: 30000,
        },
        nanocoder: {
            transport: "stdio",
            command: "npx",
            args: ["-y", "@upstash/context7-mcp"],
            env: { CONTEXT7_API_KEY: "${CONTEXT7_API_KEY:-}" },
        },
        vscode: {
            command: "npx",
            args: ["-y", "@upstash/context7-mcp"],
            env: { CONTEXT7_API_KEY: "${env:CONTEXT7_API_KEY}" },
        },
        cursor: {
            command: "npx",
            args: ["-y", "@upstash/context7-mcp"],
            env: { CONTEXT7_API_KEY: "${env:CONTEXT7_API_KEY}" },
        },
    });
    if (HAS_UVX) {
        servers.set("fetch", {
            summary: "Fetch web pages as markdown (reference server)",
            claude: { type: "stdio", command: "uvx", args: ["mcp-server-fetch"] },
            codex: { command: "uvx", args: ["mcp-server-fetch"] },
            opencode: {
                type: "local",
                command: ["uvx", "mcp-server-fetch"],
                enabled: true,
                timeout: 30000,
            },
            nanocoder: { transport: "stdio", command: "uvx", args: ["mcp-server-fetch"] },
            vscode: { command: "uvx", args: ["mcp-server-fetch"] },
            cursor: { command: "uvx", args: ["mcp-server-fetch"] },
        });
        servers.set("git", {
            summary: "Local git repository operations (reference server)",
            claude: { type: "stdio", command: "uvx", args: ["mcp-server-git"] },
            codex: { command: "uvx", args: ["mcp-server-git"] },
            opencode: {
                type: "local",
                command: ["uvx", "mcp-server-git"],
                enabled: true,
                timeout: 30000,
            },
            nanocoder: { transport: "stdio", command: "uvx", args: ["mcp-server-git"] },
            vscode: { command: "uvx", args: ["mcp-server-git"] },
            cursor: { command: "uvx", args: ["mcp-server-git"] },
        });
    }
    servers.set("zai-vision", {
        summary: "Z.ai vision MCP: screenshot/diagram/image & video analysis",
        claude: {
            type: "stdio",
            command: "npx",
            args: ["-y", "@z_ai/mcp-server"],
            env: { ZAI_API_KEY: "${ZAI_API_KEY:-}", Z_AI_MODE: "ZAI" },
        },
        codex: {
            command: "npx",
            args: ["-y", "@z_ai/mcp-server"],
            env_vars: ["ZAI_API_KEY", "Z_AI_MODE"],
        },
        opencode: {
            type: "local",
            command: ["npx", "-y", "@z_ai/mcp-server"],
            enabled: true,
            timeout: 120000,
            environment: {
                ZAI_API_KEY: "{env:ZAI_API_KEY}",
                Z_AI_MODE: "ZAI",
            },
        },
        nanocoder: {
            transport: "stdio",
            command: "npx",
            args: ["-y", "@z_ai/mcp-server"],
            env: { ZAI_API_KEY: "${ZAI_API_KEY:-}", Z_AI_MODE: "ZAI" },
        },
        vscode: {
            command: "npx",
            args: ["-y", "@z_ai/mcp-server"],
            env: { ZAI_API_KEY: "${env:ZAI_API_KEY}", Z_AI_MODE: "ZAI" },
        },
        cursor: {
            command: "npx",
            args: ["-y", "@z_ai/mcp-server"],
            env: { ZAI_API_KEY: "${env:ZAI_API_KEY}", Z_AI_MODE: "ZAI" },
        },
    });
    servers.set("zai-web-search", {
        summary: "Z.ai web-search-prime (remote streamable HTTP)",
        claude: {
            type: "http",
            url: "https://api.z.ai/api/mcp/web_search_prime/mcp",
            headers: { Authorization: "Bearer ${ZAI_API_KEY:-}" },
        },
        codex: {
            url: "https://api.z.ai/api/mcp/web_search_prime/mcp",
            bearer_token_env_var: "ZAI_API_KEY",
        },
        opencode: {
            type: "remote",
            url: "https://api.z.ai/api/mcp/web_search_prime/mcp",
            enabled: true,
            timeout: 120000,
            headers: { Authorization: "Bearer {env:ZAI_API_KEY}" },
        },
        nanocoder: {
            transport: "http",
            url: "https://api.z.ai/api/mcp/web_search_prime/mcp",
            headers: { Authorization: "Bearer ${ZAI_API_KEY:-}" },
        },
        vscode: {
            type: "http",
            url: "https://api.z.ai/api/mcp/web_search_prime/mcp",
            headers: { Authorization: "Bearer ${env:ZAI_API_KEY}" },
        },
        cursor: {
            url: "https://api.z.ai/api/mcp/web_search_prime/mcp",
            headers: { Authorization: "Bearer ${env:ZAI_API_KEY}" },
        },
    });
    servers.set("zai-image", {
        summary: "Z.ai image generation (glm-image) wrapped as local MCP",
        claude: {
            type: "stdio",
            command: NODE_BIN,
            args: [ZAI_IMAGE_SCRIPT],
            env: { ZAI_API_KEY: "${ZAI_API_KEY:-}" },
        },
        codex: {
            command: NODE_BIN,
            args: [ZAI_IMAGE_SCRIPT],
            env_vars: ["ZAI_API_KEY"],
        },
        opencode: {
            type: "local",
            command: [NODE_BIN, ZAI_IMAGE_SCRIPT],
            enabled: true,
            timeout: 300000,
            environment: { ZAI_API_KEY: "{env:ZAI_API_KEY}" },
        },
        nanocoder: {
            transport: "stdio",
            command: NODE_BIN,
            args: [ZAI_IMAGE_SCRIPT],
            env: { ZAI_API_KEY: "${ZAI_API_KEY:-}" },
        },
        vscode: {
            command: NODE_BIN,
            args: [ZAI_IMAGE_SCRIPT],
            env: { ZAI_API_KEY: "${env:ZAI_API_KEY}" },
        },
    });
    return servers;
}

// ---------------------------------------------------------------------------
// Writers
// ---------------------------------------------------------------------------

function writeAtomic(filePath, contents, mode = 0o600) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    const temp = `${filePath}.tmp-${process.pid}`;
    fs.writeFileSync(temp, contents, { mode });
    fs.renameSync(temp, filePath);
    try {
        fs.chmodSync(filePath, mode);
    } catch {
        // chmod best-effort (Windows).
    }
}

function readJson(filePath) {
    try {
        return JSON.parse(fs.readFileSync(filePath, "utf8"));
    } catch {
        return null;
    }
}

function writeMergedJsonMap(filePath, rootKey, managedEntries, mode = 0o600) {
    const existing = readJson(filePath) || {};
    const bucket = { ...(existing[rootKey] || {}) };
    for (const [name, entry] of Object.entries(managedEntries)) {
        bucket[name] = entry;
    }
    const next = { ...existing, [rootKey]: bucket };
    const before = JSON.stringify(existing[rootKey] || {}, null, 2);
    const after = JSON.stringify(bucket, null, 2);
    const changed = before !== after;
    if (changed && !CHECK_ONLY) {
        writeAtomic(filePath, `${JSON.stringify(next, null, 2)}\n`, mode);
    }
    return changed;
}

const TOML_BEGIN = "# >>> dataviz-mcp (managed by npm run mcp:sync) >>>";
const TOML_END = "# <<< dataviz-mcp <<<";

function codexServerTable(name, definition) {
    const lines = [`[mcp_servers.${name}]`];
    if (definition.url) {
        lines.push(`url = "${definition.url}"`);
        if (definition.bearer_token_env_var) {
            lines.push(`bearer_token_env_var = "${definition.bearer_token_env_var}"`);
        }
        if (definition.http_headers) {
            lines.push("");
            lines.push(`[mcp_servers.${name}.http_headers]`);
            for (const [header, value] of Object.entries(definition.http_headers)) {
                lines.push(`${JSON.stringify(header)} = ${JSON.stringify(value)}`);
            }
        }
    } else {
        lines.push(`command = "${definition.command}"`);
        lines.push(`args = [${definition.args.map((arg) => JSON.stringify(arg)).join(", ")}]`);
        if (definition.env_vars?.length) {
            lines.push(
                `env_vars = [${definition.env_vars.map((v) => JSON.stringify(v)).join(", ")}]`,
            );
        }
        if (definition.startup_timeout_sec) {
            lines.push(`startup_timeout_sec = ${definition.startup_timeout_sec}`);
        }
    }
    return lines.join("\n");
}

const MANAGED_TOML_RE = new RegExp(
    `\\n?${TOML_BEGIN.replace(/[()]/g, "\\$&")}[\\s\\S]*?${TOML_END}\\n?`,
    "g",
);

function stripManagedTomlBlocks(text) {
    return text.replace(MANAGED_TOML_RE, "\n").trimEnd();
}

function writeCodexConfig(managedEntries) {
    // Codex reads $CODEX_HOME/config.toml (default ~/.codex/config.toml).
    // NOTE: Codex >= 0.153 additionally deep-merges a trusted workspace
    // `.codex/config.toml` into the effective config (project trust recorded
    // via [projects."<path>"] trust_level in the home config). MCP servers
    // therefore live solely in the home config — per-machine, with the
    // container/host-appropriate URL — and the workspace copy is kept MCP-free
    // (pruneCodexWorkspaceConfig): a stale stdio entry there conflicts with the
    // home config's HTTP entry and hard-fails every codex startup with
    // "url is not supported for stdio in `mcp_servers.unity`".
    //
    // This workspace's trust entry is (re)written AFTER the managed block so
    // syncs never drop it (older managed outputs embedded it inside the block,
    // and each sync stripped it); the same rewrite also migrates such embedded
    // entries out. Other projects' trust entries are left untouched.
    const codexHome = process.env.CODEX_HOME || path.join(os.homedir(), ".codex");
    const filePath = path.join(codexHome, "config.toml");
    let existing = "";
    try {
        existing = fs.readFileSync(filePath, "utf8");
    } catch {
        existing = "";
    }
    const trustHeader = `[projects.${JSON.stringify(WORKSPACE_ROOT)}]`;
    const trustBlock = `${trustHeader}\ntrust_level = "trusted"`;
    const trustEntryRe = new RegExp(
        `\\n?${trustHeader.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}(?:[^[]*)`,
        "g",
    );
    const stripped = stripManagedTomlBlocks(existing)
        .replace(trustEntryRe, "\n")
        .trimEnd();
    const block = [
        "",
        TOML_BEGIN,
        ...Object.entries(managedEntries).map(([name, definition]) =>
            codexServerTable(name, definition),
        ),
        TOML_END,
        "",
    ].join("\n");
    const next = `${stripped}${block}${trustBlock}\n`;
    const changed = next !== existing;
    if (changed && !CHECK_ONLY) {
        writeAtomic(filePath, next, 0o600);
    }
    return changed;
}

// Codex >= 0.153 deep-merges a trusted workspace `.codex/config.toml` into the
// effective config, so MCP servers shipped here would fight the ones managed
// in $CODEX_HOME/config.toml (a transport mismatch there — e.g. a leftover
// stdio unity entry — hard-fails config loading at every codex startup). Strip
// managed blocks; delete the file once nothing user-owned remains. If the
// remainder still defines MCP servers, surface a warning instead of touching
// user-owned content.
function pruneCodexWorkspaceConfig() {
    const filePath = path.join(WORKSPACE_ROOT, ".codex", "config.toml");
    let existing;
    try {
        existing = fs.readFileSync(filePath, "utf8");
    } catch {
        return { changed: false, note: "" };
    }
    const remainder = stripManagedTomlBlocks(existing);
    if (remainder.trim().length === 0) {
        if (!CHECK_ONLY) {
            fs.rmSync(filePath, { force: true });
            try {
                fs.rmdirSync(path.dirname(filePath));
            } catch {
                // `.codex` still has other content — leave the folder alone.
            }
        }
        return {
            changed: true,
            note: "stale managed block removed (MCP lives in $CODEX_HOME/config.toml; Codex 0.153+ merges this file)",
        };
    }
    if (remainder !== existing) {
        if (!CHECK_ONLY) {
            writeAtomic(filePath, `${remainder}\n`, 0o600);
        }
        return { changed: true, note: "managed block stripped; user content kept" };
    }
    return {
        changed: false,
        note: /\[mcp_servers\./.test(remainder)
            ? "has user-defined [mcp_servers.*] entries — transports must match $CODEX_HOME/config.toml or Codex 0.153+ merge hard-fails startup"
            : "",
    };
}

function writeClaudeSettings() {
    const filePath = path.join(WORKSPACE_ROOT, ".claude", "settings.local.json");
    const existing = readJson(filePath) || {};
    const desired = { ...existing, enableAllProjectMcpServers: true };
    const changed = JSON.stringify(existing) !== JSON.stringify(desired);
    if (changed && !CHECK_ONLY) {
        writeAtomic(filePath, `${JSON.stringify(desired, null, 2)}\n`, 0o600);
    }
    return changed;
}

// Project-scope .mcp.json servers stay "Pending approval" until the folder is
// trusted and the servers are approved. Record the same machine-local state
// (~/.claude.json projects entry) that the interactive dialogs write.
function writeClaudeApprovals(managedNames) {
    const homeDirectory = process.env.HOME || os.homedir();
    const filePath = path.join(homeDirectory, ".claude.json");
    let existing = {};
    try {
        existing = JSON.parse(fs.readFileSync(filePath, "utf8"));
    } catch {
        existing = {};
    }
    const projects = { ...(existing.projects || {}) };
    const projectKey = WORKSPACE_ROOT;
    const entry = { ...(projects[projectKey] || {}) };
    const enabled = [...new Set([...(entry.enabledMcpjsonServers || []), ...managedNames])].sort();
    const desired = { ...entry, hasTrustDialogAccepted: true, enabledMcpjsonServers: enabled };
    const changed =
        JSON.stringify(projects[projectKey] || {}) !== JSON.stringify(desired);
    if (changed && !CHECK_ONLY) {
        projects[projectKey] = desired;
        writeAtomic(filePath, `${JSON.stringify({ ...existing, projects }, null, 2)}\n`, 0o600);
    }
    return changed;
}

// Nanocoder gates startup behind a per-directory trust dialog, which blocks
// non-interactive runs. Seed the same `trustedDirectories` entry its own trust
// dialog writes (user-level nanocoder-preferences.json, honoring
// NANOCODER_CONFIG_DIR), mirroring the Claude approval seeding above.
function writeNanocoderPreferences() {
    const configDir = process.env.NANOCODER_CONFIG_DIR
        || path.join(os.homedir(), ".config", "nanocoder");
    const filePath = path.join(configDir, "nanocoder-preferences.json");
    const existing = readJson(filePath) || {};
    const trusted = [...new Set([...(existing.trustedDirectories || []), WORKSPACE_ROOT])].sort();
    const desired = { ...existing, trustedDirectories: trusted };
    const changed = JSON.stringify(existing) !== JSON.stringify(desired);
    if (changed && !CHECK_ONLY) {
        writeAtomic(filePath, `${JSON.stringify(desired, null, 2)}\n`, 0o600);
    }
    return changed;
}

// Nanocoder's provider wizard writes agents.config.json; without a provider
// the CLI only offers the setup wizard and cannot run. Register the same
// custom providers the devcontainer's zai/openrouter launchers target, keyed
// by env-var reference (nanocoder's substituteEnvVars supports
// ${VAR:-default}; no secrets land on disk). User-added providers are kept.
function writeNanocoderProviders() {
    const filePath = path.join(WORKSPACE_ROOT, "agents.config.json");
    const existing = readJson(filePath) || {};
    const managedProviders = [
        {
            // Z.ai's OpenAI-compatible chat endpoint (/api/paas/v4), not
            // /api/v1 — that one only serves the Responses API, which
            // nanocoder's OpenAI SDK cannot speak (403 model_access_denied).
            name: "zai",
            baseUrl: "https://api.z.ai/api/paas/v4",
            apiKey: "${ZAI_API_KEY}",
            models: ["glm-5.3", "glm-5.3-flash"],
            timeout: 300000,
        },
        {
            name: "openrouter",
            baseUrl: "https://openrouter.ai/api/v1",
            apiKey: "${OPEN_ROUTER_API_KEY}",
            // Plain slug: nanocoder rejects the codex-style "~" alias prefix.
            models: ["openai/gpt-5-mini"],
            timeout: 300000,
        },
    ];
    const userProviders = (existing.nanocoder?.providers || []).filter(
        (provider) => !managedProviders.some((managed) => managed.name === provider.name),
    );
    const nanocoder = {
        ...(existing.nanocoder || {}),
        providers: [...managedProviders, ...userProviders],
    };
    const next = { ...existing, nanocoder };
    const changed = JSON.stringify(existing) !== JSON.stringify(next);
    if (changed && !CHECK_ONLY) {
        writeAtomic(filePath, `${JSON.stringify(next, null, 2)}\n`, 0o600);
    }
    return changed;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
    const unityToken = ensureUnityMcpToken();
    const zaiKeyStatus = ensureZaiKeyAlias();
    const catalog = buildCatalog();

    const managedClaude = {};
    const managedCodex = {};
    const managedOpencode = {};
    const managedNanocoder = {};
    const managedVscode = {};
    const managedCursor = {};
    for (const [name, definition] of catalog) {
        managedClaude[name] = definition.claude;
        managedCodex[name] = definition.codex;
        managedOpencode[name] = definition.opencode;
        managedNanocoder[name] = definition.nanocoder;
        managedVscode[name] = definition.vscode;
        if (definition.cursor) managedCursor[name] = definition.cursor;
    }

    const results = [];
    let codexWorkspaceOutcome = { changed: false, note: "" };
    const plan = [
        {
            label: "Claude Code (.mcp.json + project approval)",
            write: () => {
                const changed =
                    writeMergedJsonMap(
                        path.join(WORKSPACE_ROOT, ".mcp.json"),
                        "mcpServers",
                        managedClaude,
                    ) |
                    writeClaudeSettings() |
                    writeClaudeApprovals(Object.keys(managedClaude));
                return Boolean(changed);
            },
        },
        {
            label: `Codex (${process.env.CODEX_HOME || "~/.codex"}/config.toml managed block)`,
            write: () => writeCodexConfig(managedCodex),
        },
        {
            label: "Codex workspace (.codex/config.toml pruned — Codex 0.153+ merges it)",
            write: () => {
                codexWorkspaceOutcome = pruneCodexWorkspaceConfig();
                return codexWorkspaceOutcome.changed;
            },
            after: () => {
                if (codexWorkspaceOutcome.note) {
                    results.push(
                        `${codexWorkspaceOutcome.changed ? "✅" : "·"}   ↳ ${codexWorkspaceOutcome.note}`,
                    );
                }
            },
        },
        {
            label: "OpenCode (opencode.json mcp block)",
            write: () =>
                writeMergedJsonMap(
                    path.join(WORKSPACE_ROOT, "opencode.json"),
                    "mcp",
                    managedOpencode,
                ),
        },
        {
            label: "Nanocoder (.nanocoder/mcp.json + trust seed + providers)",
            write: () =>
                Boolean(
                    writeMergedJsonMap(
                        path.join(WORKSPACE_ROOT, ".nanocoder", "mcp.json"),
                        "mcpServers",
                        managedNanocoder,
                    ) | writeNanocoderPreferences() | writeNanocoderProviders(),
                ),
        },
        {
            label: "VS Code (.vscode/mcp.json)",
            write: () =>
                writeMergedJsonMap(
                    path.join(WORKSPACE_ROOT, ".vscode", "mcp.json"),
                    "servers",
                    managedVscode,
                ),
        },
        {
            // Project scope: Cursor on the host reads this shared file. It
            // launches commands on the host, so stdio servers must reference
            // host-visible binaries (`unity`, npx, uvx) — container-absolute
            // paths (zai-image) are intentionally omitted here.
            label: "Cursor (.cursor/mcp.json, project scope)",
            write: () =>
                writeMergedJsonMap(
                    path.join(WORKSPACE_ROOT, ".cursor", "mcp.json"),
                    "mcpServers",
                    managedCursor,
                    0o644,
                ),
        },
    ];

    for (const entry of plan) {
        try {
            const changed = entry.write();
            results.push(`${changed ? "✅" : "·"} ${entry.label}${changed && !CHECK_ONLY ? " updated" : ""}`);
            if (entry.after) entry.after();
        } catch (error) {
            results.push(`❌ ${entry.label}: ${error.message}`);
        }
    }

    const container = isContainer();
    console.log("");
    console.log("╔════════════════════════════════════════════════════════════════╗");
    console.log("║                MCP Server Configuration                        ║");
    console.log("╚════════════════════════════════════════════════════════════════╝");
    for (const line of results) console.log(`  ${line}`);
    console.log("");
    console.log(`  Servers: ${[...catalog.keys()].join(", ")}`);
    if (!HAS_UVX) {
        console.log("  (fetch/git skipped: uvx not found on PATH)");
    }
    console.log(
        `  UNITY_MCP_TOKEN: ${unityToken && unityToken !== "(generated)" ? "configured" : "OPEN (no token)"}`,
    );
    console.log(
        `  ZAI_API_KEY: ${zaiKeyStatus === "missing" ? "MISSING (zai-* servers will fail auth)" : zaiKeyStatus}`,
    );
    console.log(`  Environment: ${container ? "devcontainer" : "host"} (unity bridge host: ${container ? "host.docker.internal" : "127.0.0.1"})`);
    console.log(
        `  Unity MCP: official Unity CLI (~140 tools) via ${UNITY_MCP_URL} — start the bridge with \`npm run unity:mcp:host\` on the host.`,
    );
    console.log(
        "  Host GUI clients (Cursor/Windsurf/Claude Desktop): run `unity mcp configure <client>` on the host for native stdio.",
    );
    console.log("");
    console.log("  Restart your agent CLIs (or run /mcp) to pick up changes.");
    console.log("");
}

main();
